/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/basic-layout/BaseHeader.vue')['default']
    BaseSide: typeof import('./src/components/basic-layout/BaseSide.vue')['default']
    BasicBadge: typeof import('./src/components/basic-badge/src/BasicBadge.vue')['default']
    BasicCheckboxGroup: typeof import('./src/components/basic-checkbox/BasicCheckboxGroup.vue')['default']
    BasicCopy: typeof import('./src/components/basic-copy/src/BasicCopy.vue')['default']
    BasicDisplay: typeof import('./src/components/basic-display/src/BasicDisplay.vue')['default']
    BasicForm: typeof import('./src/components/basic-form/src/BasicForm.vue')['default']
    BasicRadioGroup: typeof import('./src/components/basic-radio/BasicRadioGroup.vue')['default']
    BasicRender: typeof import('./src/components/basic-render/src/BasicRender.vue')['default']
    BasicSelect: typeof import('./src/components/basic-select/BasicSelect.vue')['default']
    BasicTable: typeof import('./src/components/basic-table/src/BasicTable.vue')['default']
    BasicUpload: typeof import('./src/components/basic-upload/BasicUpload.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Src: typeof import('./src/components/basic-pagination/src/index.vue')['default']
    TableBody: typeof import('./src/components/basic-table/src/components/TableBody.vue')['default']
    TableColumn: typeof import('./src/components/basic-table/src/components/TableColumn.vue')['default']
    TableColumnDisplay: typeof import('./src/components/basic-table/src/components/TableColumnDisplay.vue')['default']
  }
}
